// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dister.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_DEFAULT               Message_MessageType = 0
	Message_REGISTER_REQUEST      Message_MessageType = 1
	Message_REGISTER_RESPONSE     Message_MessageType = 2
	Message_UNREGISTER_REQUEST    Message_MessageType = 3
	Message_UNREGISTER_RESPONSE   Message_MessageType = 4
	Message_TASK_PROCESS_REQUEST  Message_MessageType = 5
	Message_TASK_PROCESS_RESPONSE Message_MessageType = 6
	Message_PING_REQUEST          Message_MessageType = 700
	Message_PING_RESPONSE         Message_MessageType = 701
)

var Message_MessageType_name = map[int32]string{
	0:   "DEFAULT",
	1:   "REGISTER_REQUEST",
	2:   "REGISTER_RESPONSE",
	3:   "UNREGISTER_REQUEST",
	4:   "UNREGISTER_RESPONSE",
	5:   "TASK_PROCESS_REQUEST",
	6:   "TASK_PROCESS_RESPONSE",
	700: "PING_REQUEST",
	701: "PING_RESPONSE",
}

var Message_MessageType_value = map[string]int32{
	"DEFAULT":               0,
	"REGISTER_REQUEST":      1,
	"REGISTER_RESPONSE":     2,
	"UNREGISTER_REQUEST":    3,
	"UNREGISTER_RESPONSE":   4,
	"TASK_PROCESS_REQUEST":  5,
	"TASK_PROCESS_RESPONSE": 6,
	"PING_REQUEST":          700,
	"PING_RESPONSE":         701,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{1, 0}
}

type Validator_ValidType int32

const (
	// less than
	Validator_LT Validator_ValidType = 0
	// less than or equal to
	Validator_LE Validator_ValidType = 1
	// equal to
	Validator_EQ Validator_ValidType = 2
	// not equal to
	Validator_NE Validator_ValidType = 3
	// greater than or equal to
	Validator_GE Validator_ValidType = 4
	// greater than
	Validator_GT Validator_ValidType = 5
	// in
	Validator_IN Validator_ValidType = 6
)

var Validator_ValidType_name = map[int32]string{
	0: "LT",
	1: "LE",
	2: "EQ",
	3: "NE",
	4: "GE",
	5: "GT",
	6: "IN",
}

var Validator_ValidType_value = map[string]int32{
	"LT": 0,
	"LE": 1,
	"EQ": 2,
	"NE": 3,
	"GE": 4,
	"GT": 5,
	"IN": 6,
}

func (x Validator_ValidType) String() string {
	return proto.EnumName(Validator_ValidType_name, int32(x))
}

func (Validator_ValidType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{4, 0}
}

type Task_Method int32

const (
	Task_GET  Task_Method = 0
	Task_POST Task_Method = 1
)

var Task_Method_name = map[int32]string{
	0: "GET",
	1: "POST",
}

var Task_Method_value = map[string]int32{
	"GET":  0,
	"POST": 1,
}

func (x Task_Method) String() string {
	return proto.EnumName(Task_Method_name, int32(x))
}

func (Task_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{5, 0}
}

type TaskProcessResponse_PrepareType int32

const (
	TaskProcessResponse_SUCCESS TaskProcessResponse_PrepareType = 0
	TaskProcessResponse_FAILD   TaskProcessResponse_PrepareType = 1
)

var TaskProcessResponse_PrepareType_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILD",
}

var TaskProcessResponse_PrepareType_value = map[string]int32{
	"SUCCESS": 0,
	"FAILD":   1,
}

func (x TaskProcessResponse_PrepareType) String() string {
	return proto.EnumName(TaskProcessResponse_PrepareType_name, int32(x))
}

func (TaskProcessResponse_PrepareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{6, 0}
}

// A list of messages to be transmitted together.
type MessageList struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{0}
}

func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (m *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(m, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// The message passed between the validator and client, containing the
// header fields and content.
type Message struct {
	// content.
	MessageType Message_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=protos.Message_MessageType" json:"message_type,omitempty"`
	// The identifier used to correlate response messages to their related
	// request messages.  correlation_id should be set to a random string
	// for messages which are not responses to previously sent messages.  For
	// response messages, correlation_id should be set to the same string as
	// contained in the request message.
	CorrelationId        string   `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_DEFAULT
}

func (m *Message) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type RegisterRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cup                  int32    `protobuf:"varint,2,opt,name=cup,proto3" json:"cup,omitempty"`
	Mem                  int32    `protobuf:"varint,3,opt,name=mem,proto3" json:"mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterRequest) GetCup() int32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

func (m *RegisterRequest) GetMem() int32 {
	if m != nil {
		return m.Mem
	}
	return 0
}

type TaskProcessRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Threads              int32    `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	CountLimit           int32    `protobuf:"varint,3,opt,name=count_limit,json=countLimit,proto3" json:"count_limit,omitempty"`
	TimeLimit            int32    `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	Task                 *Task    `protobuf:"bytes,5,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskProcessRequest) Reset()         { *m = TaskProcessRequest{} }
func (m *TaskProcessRequest) String() string { return proto.CompactTextString(m) }
func (*TaskProcessRequest) ProtoMessage()    {}
func (*TaskProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{3}
}

func (m *TaskProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProcessRequest.Unmarshal(m, b)
}
func (m *TaskProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProcessRequest.Marshal(b, m, deterministic)
}
func (m *TaskProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProcessRequest.Merge(m, src)
}
func (m *TaskProcessRequest) XXX_Size() int {
	return xxx_messageInfo_TaskProcessRequest.Size(m)
}
func (m *TaskProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProcessRequest proto.InternalMessageInfo

func (m *TaskProcessRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskProcessRequest) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *TaskProcessRequest) GetCountLimit() int32 {
	if m != nil {
		return m.CountLimit
	}
	return 0
}

func (m *TaskProcessRequest) GetTimeLimit() int32 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *TaskProcessRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type Validator struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vt                   Validator_ValidType `protobuf:"varint,2,opt,name=vt,proto3,enum=protos.Validator_ValidType" json:"vt,omitempty"`
	Value                string              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{4}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Validator) GetVt() Validator_ValidType {
	if m != nil {
		return m.Vt
	}
	return Validator_LT
}

func (m *Validator) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Task struct {
	Url                  string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path                 string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               Task_Method  `protobuf:"varint,3,opt,name=method,proto3,enum=protos.Task_Method" json:"method,omitempty"`
	Body                 []byte       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Script               string       `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Vs                   []*Validator `protobuf:"bytes,6,rep,name=vs,proto3" json:"vs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{5}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Task) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Task) GetMethod() Task_Method {
	if m != nil {
		return m.Method
	}
	return Task_GET
}

func (m *Task) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Task) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Task) GetVs() []*Validator {
	if m != nil {
		return m.Vs
	}
	return nil
}

type TaskProcessResponse struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pt                   TaskProcessResponse_PrepareType `protobuf:"varint,2,opt,name=pt,proto3,enum=protos.TaskProcessResponse_PrepareType" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TaskProcessResponse) Reset()         { *m = TaskProcessResponse{} }
func (m *TaskProcessResponse) String() string { return proto.CompactTextString(m) }
func (*TaskProcessResponse) ProtoMessage()    {}
func (*TaskProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{6}
}

func (m *TaskProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProcessResponse.Unmarshal(m, b)
}
func (m *TaskProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProcessResponse.Marshal(b, m, deterministic)
}
func (m *TaskProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProcessResponse.Merge(m, src)
}
func (m *TaskProcessResponse) XXX_Size() int {
	return xxx_messageInfo_TaskProcessResponse.Size(m)
}
func (m *TaskProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProcessResponse proto.InternalMessageInfo

func (m *TaskProcessResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskProcessResponse) GetPt() TaskProcessResponse_PrepareType {
	if m != nil {
		return m.Pt
	}
	return TaskProcessResponse_SUCCESS
}

func init() {
	proto.RegisterEnum("protos.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("protos.Validator_ValidType", Validator_ValidType_name, Validator_ValidType_value)
	proto.RegisterEnum("protos.Task_Method", Task_Method_name, Task_Method_value)
	proto.RegisterEnum("protos.TaskProcessResponse_PrepareType", TaskProcessResponse_PrepareType_name, TaskProcessResponse_PrepareType_value)
	proto.RegisterType((*MessageList)(nil), "protos.MessageList")
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*RegisterRequest)(nil), "protos.RegisterRequest")
	proto.RegisterType((*TaskProcessRequest)(nil), "protos.TaskProcessRequest")
	proto.RegisterType((*Validator)(nil), "protos.Validator")
	proto.RegisterType((*Task)(nil), "protos.Task")
	proto.RegisterType((*TaskProcessResponse)(nil), "protos.TaskProcessResponse")
}

func init() { proto.RegisterFile("dister.proto", fileDescriptor_ffb07b0a572790a9) }

var fileDescriptor_ffb07b0a572790a9 = []byte{
	// 689 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6e, 0xda, 0x4a,
	0x10, 0x8e, 0x17, 0x6c, 0xc2, 0x40, 0x88, 0x33, 0xf9, 0x39, 0x3e, 0x27, 0x3a, 0x3a, 0x1c, 0x4b,
	0x51, 0x51, 0x23, 0x71, 0x41, 0x2b, 0x55, 0xea, 0x45, 0xa5, 0x28, 0x71, 0x10, 0x2a, 0x21, 0x64,
	0x0d, 0xbd, 0x45, 0x0e, 0x5e, 0x25, 0x56, 0xf0, 0x4f, 0xbd, 0x0b, 0x52, 0x1e, 0xa0, 0xef, 0xd1,
	0xbb, 0xbe, 0x44, 0x7b, 0xd9, 0x37, 0xe8, 0x0b, 0xf4, 0x4d, 0xaa, 0x5d, 0x2f, 0x94, 0x10, 0xf5,
	0x6a, 0x66, 0xbe, 0xf9, 0xf1, 0xb7, 0xb3, 0xdf, 0x1a, 0xea, 0x61, 0xc4, 0x05, 0xcb, 0xdb, 0x59,
	0x9e, 0x8a, 0x14, 0x2d, 0x65, 0xb8, 0xfb, 0x16, 0x6a, 0x57, 0x8c, 0xf3, 0xe0, 0x8e, 0xf5, 0x23,
	0x2e, 0xf0, 0x14, 0xb6, 0xe3, 0x22, 0xe4, 0x8e, 0xd1, 0x2c, 0xb5, 0x6a, 0x9d, 0xdd, 0xa2, 0x81,
	0xb7, 0x75, 0x19, 0x5d, 0x15, 0xb8, 0x3f, 0x09, 0x54, 0x34, 0x8a, 0xef, 0xa0, 0xae, 0xf1, 0x89,
	0x78, 0xcc, 0x98, 0x63, 0x34, 0x8d, 0x56, 0xa3, 0x73, 0xbc, 0xd1, 0xbc, 0xb4, 0xa3, 0xc7, 0x8c,
	0xd1, 0x5a, 0xfc, 0x3b, 0xc0, 0x13, 0x68, 0x4c, 0xd3, 0x3c, 0x67, 0xb3, 0x40, 0x44, 0x69, 0x32,
	0x89, 0x42, 0x87, 0x34, 0x8d, 0x56, 0x95, 0xee, 0xac, 0xa1, 0xbd, 0x10, 0x1d, 0xa8, 0x4c, 0xd3,
	0x44, 0xb0, 0x44, 0x38, 0xa5, 0xa6, 0xd1, 0xaa, 0xd3, 0x65, 0xe8, 0xfe, 0x30, 0x56, 0x27, 0x51,
	0x03, 0x6b, 0x50, 0xb9, 0xf0, 0x2e, 0xcf, 0xc6, 0xfd, 0x91, 0xbd, 0x85, 0x07, 0x60, 0x53, 0xaf,
	0xdb, 0xf3, 0x47, 0x1e, 0x9d, 0x50, 0xef, 0x66, 0xec, 0xf9, 0x23, 0xdb, 0xc0, 0x43, 0xd8, 0x5b,
	0x43, 0xfd, 0xe1, 0xf5, 0xc0, 0xf7, 0x6c, 0x82, 0x47, 0x80, 0xe3, 0xc1, 0xb3, 0xf2, 0x12, 0xfe,
	0x05, 0xfb, 0x4f, 0x70, 0xdd, 0x50, 0x46, 0x07, 0x0e, 0x46, 0x67, 0xfe, 0xfb, 0xc9, 0x90, 0x5e,
	0x9f, 0x7b, 0xbe, 0xbf, 0x6a, 0x31, 0xf1, 0x6f, 0x38, 0xdc, 0xc8, 0xe8, 0x26, 0x0b, 0xf7, 0xa0,
	0x3e, 0xec, 0x0d, 0xba, 0xab, 0xe2, 0xaf, 0x26, 0x22, 0xec, 0x68, 0x48, 0x57, 0x7d, 0x33, 0x5d,
	0x0f, 0x76, 0x29, 0xbb, 0x53, 0x37, 0x47, 0xd9, 0xc7, 0x39, 0xe3, 0x02, 0x1b, 0x40, 0xa2, 0x50,
	0x2d, 0xb8, 0x4a, 0x49, 0x14, 0xa2, 0x0d, 0xa5, 0xe9, 0x3c, 0x53, 0xfb, 0x32, 0xa9, 0x74, 0x25,
	0x12, 0xb3, 0x58, 0x6d, 0xc8, 0xa4, 0xd2, 0x75, 0x3f, 0x1b, 0x80, 0xa3, 0x80, 0x3f, 0x0c, 0xf3,
	0x74, 0xca, 0x38, 0xff, 0xd3, 0x28, 0x07, 0x2a, 0xe2, 0x3e, 0x67, 0x41, 0xc8, 0xf5, 0xb8, 0x65,
	0x88, 0xff, 0x41, 0x6d, 0x9a, 0xce, 0x13, 0x31, 0x99, 0x45, 0x71, 0x24, 0xf4, 0x68, 0x50, 0x50,
	0x5f, 0x22, 0xf8, 0x2f, 0x80, 0x88, 0x62, 0xa6, 0xf3, 0x65, 0x95, 0xaf, 0x4a, 0xa4, 0x48, 0x37,
	0xa1, 0x2c, 0x02, 0xfe, 0xe0, 0x98, 0x4d, 0xa3, 0x55, 0xeb, 0xd4, 0x97, 0xba, 0x90, 0x9c, 0xa8,
	0xca, 0xb8, 0x5f, 0x0c, 0xa8, 0x7e, 0x08, 0x66, 0x51, 0x18, 0x88, 0x34, 0x47, 0x84, 0x72, 0x12,
	0xc4, 0x4c, 0x73, 0x53, 0x3e, 0x9e, 0x02, 0x59, 0x08, 0x45, 0x6c, 0x4d, 0x59, 0xab, 0x96, 0xc2,
	0x53, 0xca, 0x22, 0x0b, 0x81, 0x07, 0x60, 0x2e, 0x82, 0xd9, 0x9c, 0x29, 0xaa, 0x55, 0x5a, 0x04,
	0xee, 0xb9, 0xfe, 0x86, 0x92, 0x88, 0x05, 0x44, 0xa9, 0x43, 0x5a, 0xcf, 0x36, 0xa4, 0xf5, 0x6e,
	0x6c, 0x22, 0xed, 0xc0, 0xb3, 0x4b, 0xd2, 0x76, 0xe5, 0xfd, 0x4a, 0x2b, 0x6f, 0xd3, 0x02, 0xd2,
	0x1b, 0xd8, 0x96, 0xfb, 0xdd, 0x80, 0xb2, 0x24, 0x2e, 0xf7, 0x3c, 0xcf, 0x67, 0x9a, 0xa3, 0x74,
	0x25, 0xed, 0x2c, 0x10, 0xf7, 0x5a, 0xbc, 0xca, 0xc7, 0x53, 0xb0, 0x62, 0x26, 0xee, 0xd3, 0x50,
	0x51, 0x69, 0x74, 0xf6, 0xd7, 0x0f, 0xdf, 0xbe, 0x52, 0x29, 0xaa, 0x4b, 0xe4, 0x80, 0xdb, 0x34,
	0x7c, 0x54, 0x0b, 0xac, 0x53, 0xe5, 0xe3, 0x11, 0x58, 0x7c, 0x9a, 0x47, 0x99, 0x50, 0xdb, 0xab,
	0x52, 0x1d, 0xe1, 0xff, 0x40, 0x16, 0xdc, 0xb1, 0xd4, 0x33, 0xdd, 0x7b, 0xb6, 0x0f, 0x4a, 0x16,
	0xdc, 0x3d, 0x06, 0xab, 0xf8, 0x00, 0x56, 0xa0, 0xd4, 0xf5, 0xe4, 0x69, 0xb7, 0xa1, 0x3c, 0xbc,
	0x96, 0xfa, 0x77, 0x3f, 0x19, 0xb0, 0xff, 0x44, 0x14, 0x3c, 0x4b, 0x13, 0xce, 0x9e, 0xa9, 0xe2,
	0x0d, 0x90, 0x6c, 0xb9, 0xf7, 0x17, 0xeb, 0xe4, 0x37, 0x1a, 0xdb, 0xc3, 0x9c, 0x65, 0x41, 0x5e,
	0xbc, 0x6e, 0x92, 0x09, 0xf7, 0x04, 0x6a, 0x6b, 0x90, 0x7c, 0x92, 0xfe, 0xf8, 0x5c, 0x3e, 0x04,
	0x7b, 0x0b, 0xab, 0x60, 0x5e, 0x9e, 0xf5, 0xfa, 0x17, 0xb6, 0xd1, 0x79, 0x0d, 0xd6, 0x85, 0x52,
	0x38, 0xbe, 0x84, 0xb2, 0xcf, 0x92, 0x10, 0x37, 0x7f, 0x3a, 0xff, 0x6c, 0x02, 0xee, 0xd6, 0x6d,
	0xf1, 0x07, 0x7b, 0xf5, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xad, 0x7f, 0x00, 0x27, 0xd8, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DisterClient is the client API for Dister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisterClient interface {
	Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error)
}

type disterClient struct {
	cc *grpc.ClientConn
}

func NewDisterClient(cc *grpc.ClientConn) DisterClient {
	return &disterClient{cc}
}

func (c *disterClient) Send(ctx context.Context, in *Message, opts ...grpc.CallOption) (*Message, error) {
	out := new(Message)
	err := c.cc.Invoke(ctx, "/protos.Dister/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DisterServer is the server API for Dister service.
type DisterServer interface {
	Send(context.Context, *Message) (*Message, error)
}

// UnimplementedDisterServer can be embedded to have forward compatible implementations.
type UnimplementedDisterServer struct {
}

func (*UnimplementedDisterServer) Send(ctx context.Context, req *Message) (*Message, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}

func RegisterDisterServer(s *grpc.Server, srv DisterServer) {
	s.RegisterService(&_Dister_serviceDesc, srv)
}

func _Dister_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DisterServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Dister/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DisterServer).Send(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Dister",
	HandlerType: (*DisterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _Dister_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dister.proto",
}
