// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dister.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_MessageType int32

const (
	Message_REGISTER_REQUEST      Message_MessageType = 0
	Message_REGISTER_RESPONSE     Message_MessageType = 1
	Message_TASK_PROCESS_REQUEST  Message_MessageType = 2
	Message_TASK_PROCESS_RESPONSE Message_MessageType = 3
	Message_TASK_START_REQUEST    Message_MessageType = 4
	Message_TASK_START_RESPONSE   Message_MessageType = 5
	Message_PING_REQUEST          Message_MessageType = 700
	Message_PING_RESPONSE         Message_MessageType = 701
)

var Message_MessageType_name = map[int32]string{
	0:   "REGISTER_REQUEST",
	1:   "REGISTER_RESPONSE",
	2:   "TASK_PROCESS_REQUEST",
	3:   "TASK_PROCESS_RESPONSE",
	4:   "TASK_START_REQUEST",
	5:   "TASK_START_RESPONSE",
	700: "PING_REQUEST",
	701: "PING_RESPONSE",
}

var Message_MessageType_value = map[string]int32{
	"REGISTER_REQUEST":      0,
	"REGISTER_RESPONSE":     1,
	"TASK_PROCESS_REQUEST":  2,
	"TASK_PROCESS_RESPONSE": 3,
	"TASK_START_REQUEST":    4,
	"TASK_START_RESPONSE":   5,
	"PING_REQUEST":          700,
	"PING_RESPONSE":         701,
}

func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}

func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{1, 0}
}

type Validator_ValidType int32

const (
	// less than
	Validator_LT Validator_ValidType = 0
	// less than or equal to
	Validator_LE Validator_ValidType = 1
	// equal to
	Validator_EQ Validator_ValidType = 2
	// not equal to
	Validator_NE Validator_ValidType = 3
	// greater than or equal to
	Validator_GE Validator_ValidType = 4
	// greater than
	Validator_GT Validator_ValidType = 5
	// in
	Validator_IN Validator_ValidType = 6
)

var Validator_ValidType_name = map[int32]string{
	0: "LT",
	1: "LE",
	2: "EQ",
	3: "NE",
	4: "GE",
	5: "GT",
	6: "IN",
}

var Validator_ValidType_value = map[string]int32{
	"LT": 0,
	"LE": 1,
	"EQ": 2,
	"NE": 3,
	"GE": 4,
	"GT": 5,
	"IN": 6,
}

func (x Validator_ValidType) String() string {
	return proto.EnumName(Validator_ValidType_name, int32(x))
}

func (Validator_ValidType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{5, 0}
}

type Task_Method int32

const (
	Task_GET  Task_Method = 0
	Task_POST Task_Method = 1
)

var Task_Method_name = map[int32]string{
	0: "GET",
	1: "POST",
}

var Task_Method_value = map[string]int32{
	"GET":  0,
	"POST": 1,
}

func (x Task_Method) String() string {
	return proto.EnumName(Task_Method_name, int32(x))
}

func (Task_Method) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{6, 0}
}

type TaskProcessResponse_PrepareType int32

const (
	TaskProcessResponse_SUCCESS TaskProcessResponse_PrepareType = 0
	TaskProcessResponse_FAILD   TaskProcessResponse_PrepareType = 1
)

var TaskProcessResponse_PrepareType_name = map[int32]string{
	0: "SUCCESS",
	1: "FAILD",
}

var TaskProcessResponse_PrepareType_value = map[string]int32{
	"SUCCESS": 0,
	"FAILD":   1,
}

func (x TaskProcessResponse_PrepareType) String() string {
	return proto.EnumName(TaskProcessResponse_PrepareType_name, int32(x))
}

func (TaskProcessResponse_PrepareType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{7, 0}
}

type PingRequest_StatueType int32

const (
	PingRequest_Busy    PingRequest_StatueType = 0
	PingRequest_Idle    PingRequest_StatueType = 1
	PingRequest_UnReady PingRequest_StatueType = 2
)

var PingRequest_StatueType_name = map[int32]string{
	0: "Busy",
	1: "Idle",
	2: "UnReady",
}

var PingRequest_StatueType_value = map[string]int32{
	"Busy":    0,
	"Idle":    1,
	"UnReady": 2,
}

func (x PingRequest_StatueType) String() string {
	return proto.EnumName(PingRequest_StatueType_name, int32(x))
}

func (PingRequest_StatueType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{10, 0}
}

// A list of messages to be transmitted together.
type MessageList struct {
	Messages             []*Message `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{0}
}

func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (m *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(m, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetMessages() []*Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

// The message passed between the validator and client, containing the
// header fields and content.
type Message struct {
	// content.
	MessageType Message_MessageType `protobuf:"varint,1,opt,name=message_type,json=messageType,proto3,enum=protos.Message_MessageType" json:"message_type,omitempty"`
	// The identifier used to correlate response messages to their related
	// request messages.  correlation_id should be set to a random string
	// for messages which are not responses to previously sent messages.  For
	// response messages, correlation_id should be set to the same string as
	// contained in the request message.
	CorrelationId        string   `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMessageType() Message_MessageType {
	if m != nil {
		return m.MessageType
	}
	return Message_REGISTER_REQUEST
}

func (m *Message) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *Message) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type RegisterRequest struct {
	Cpu                  int32    `protobuf:"varint,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Mem                  int32    `protobuf:"varint,2,opt,name=mem,proto3" json:"mem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{2}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetCpu() int32 {
	if m != nil {
		return m.Cpu
	}
	return 0
}

func (m *RegisterRequest) GetMem() int32 {
	if m != nil {
		return m.Mem
	}
	return 0
}

type RegisterResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{3}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TaskProcessRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Threads              int32    `protobuf:"varint,2,opt,name=threads,proto3" json:"threads,omitempty"`
	CountLimit           int32    `protobuf:"varint,3,opt,name=count_limit,json=countLimit,proto3" json:"count_limit,omitempty"`
	TimeLimit            int32    `protobuf:"varint,4,opt,name=time_limit,json=timeLimit,proto3" json:"time_limit,omitempty"`
	Task                 *Task    `protobuf:"bytes,5,opt,name=task,proto3" json:"task,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskProcessRequest) Reset()         { *m = TaskProcessRequest{} }
func (m *TaskProcessRequest) String() string { return proto.CompactTextString(m) }
func (*TaskProcessRequest) ProtoMessage()    {}
func (*TaskProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{4}
}

func (m *TaskProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProcessRequest.Unmarshal(m, b)
}
func (m *TaskProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProcessRequest.Marshal(b, m, deterministic)
}
func (m *TaskProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProcessRequest.Merge(m, src)
}
func (m *TaskProcessRequest) XXX_Size() int {
	return xxx_messageInfo_TaskProcessRequest.Size(m)
}
func (m *TaskProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProcessRequest proto.InternalMessageInfo

func (m *TaskProcessRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskProcessRequest) GetThreads() int32 {
	if m != nil {
		return m.Threads
	}
	return 0
}

func (m *TaskProcessRequest) GetCountLimit() int32 {
	if m != nil {
		return m.CountLimit
	}
	return 0
}

func (m *TaskProcessRequest) GetTimeLimit() int32 {
	if m != nil {
		return m.TimeLimit
	}
	return 0
}

func (m *TaskProcessRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type Validator struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vt                   Validator_ValidType `protobuf:"varint,2,opt,name=vt,proto3,enum=protos.Validator_ValidType" json:"vt,omitempty"`
	Value                string              `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{5}
}

func (m *Validator) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Validator.Unmarshal(m, b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return xxx_messageInfo_Validator.Size(m)
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Validator) GetVt() Validator_ValidType {
	if m != nil {
		return m.Vt
	}
	return Validator_LT
}

func (m *Validator) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Task struct {
	Url                  string       `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path                 string       `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method               Task_Method  `protobuf:"varint,3,opt,name=method,proto3,enum=protos.Task_Method" json:"method,omitempty"`
	Body                 []byte       `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Script               string       `protobuf:"bytes,5,opt,name=script,proto3" json:"script,omitempty"`
	Vs                   []*Validator `protobuf:"bytes,6,rep,name=vs,proto3" json:"vs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{6}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Task) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Task) GetMethod() Task_Method {
	if m != nil {
		return m.Method
	}
	return Task_GET
}

func (m *Task) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Task) GetScript() string {
	if m != nil {
		return m.Script
	}
	return ""
}

func (m *Task) GetVs() []*Validator {
	if m != nil {
		return m.Vs
	}
	return nil
}

type TaskProcessResponse struct {
	Id                   string                          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pt                   TaskProcessResponse_PrepareType `protobuf:"varint,2,opt,name=pt,proto3,enum=protos.TaskProcessResponse_PrepareType" json:"pt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TaskProcessResponse) Reset()         { *m = TaskProcessResponse{} }
func (m *TaskProcessResponse) String() string { return proto.CompactTextString(m) }
func (*TaskProcessResponse) ProtoMessage()    {}
func (*TaskProcessResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{7}
}

func (m *TaskProcessResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskProcessResponse.Unmarshal(m, b)
}
func (m *TaskProcessResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskProcessResponse.Marshal(b, m, deterministic)
}
func (m *TaskProcessResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskProcessResponse.Merge(m, src)
}
func (m *TaskProcessResponse) XXX_Size() int {
	return xxx_messageInfo_TaskProcessResponse.Size(m)
}
func (m *TaskProcessResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskProcessResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskProcessResponse proto.InternalMessageInfo

func (m *TaskProcessResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskProcessResponse) GetPt() TaskProcessResponse_PrepareType {
	if m != nil {
		return m.Pt
	}
	return TaskProcessResponse_SUCCESS
}

type TaskStartRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStartRequest) Reset()         { *m = TaskStartRequest{} }
func (m *TaskStartRequest) String() string { return proto.CompactTextString(m) }
func (*TaskStartRequest) ProtoMessage()    {}
func (*TaskStartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{8}
}

func (m *TaskStartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStartRequest.Unmarshal(m, b)
}
func (m *TaskStartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStartRequest.Marshal(b, m, deterministic)
}
func (m *TaskStartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStartRequest.Merge(m, src)
}
func (m *TaskStartRequest) XXX_Size() int {
	return xxx_messageInfo_TaskStartRequest.Size(m)
}
func (m *TaskStartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStartRequest proto.InternalMessageInfo

func (m *TaskStartRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TaskStartResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStartResponse) Reset()         { *m = TaskStartResponse{} }
func (m *TaskStartResponse) String() string { return proto.CompactTextString(m) }
func (*TaskStartResponse) ProtoMessage()    {}
func (*TaskStartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{9}
}

func (m *TaskStartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStartResponse.Unmarshal(m, b)
}
func (m *TaskStartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStartResponse.Marshal(b, m, deterministic)
}
func (m *TaskStartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStartResponse.Merge(m, src)
}
func (m *TaskStartResponse) XXX_Size() int {
	return xxx_messageInfo_TaskStartResponse.Size(m)
}
func (m *TaskStartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStartResponse proto.InternalMessageInfo

func (m *TaskStartResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PingRequest struct {
	St                   PingRequest_StatueType `protobuf:"varint,1,opt,name=st,proto3,enum=protos.PingRequest_StatueType" json:"st,omitempty"`
	Tasks                []string               `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffb07b0a572790a9, []int{10}
}

func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (m *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(m, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

func (m *PingRequest) GetSt() PingRequest_StatueType {
	if m != nil {
		return m.St
	}
	return PingRequest_Busy
}

func (m *PingRequest) GetTasks() []string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("protos.Validator_ValidType", Validator_ValidType_name, Validator_ValidType_value)
	proto.RegisterEnum("protos.Task_Method", Task_Method_name, Task_Method_value)
	proto.RegisterEnum("protos.TaskProcessResponse_PrepareType", TaskProcessResponse_PrepareType_name, TaskProcessResponse_PrepareType_value)
	proto.RegisterEnum("protos.PingRequest_StatueType", PingRequest_StatueType_name, PingRequest_StatueType_value)
	proto.RegisterType((*MessageList)(nil), "protos.MessageList")
	proto.RegisterType((*Message)(nil), "protos.Message")
	proto.RegisterType((*RegisterRequest)(nil), "protos.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "protos.RegisterResponse")
	proto.RegisterType((*TaskProcessRequest)(nil), "protos.TaskProcessRequest")
	proto.RegisterType((*Validator)(nil), "protos.Validator")
	proto.RegisterType((*Task)(nil), "protos.Task")
	proto.RegisterType((*TaskProcessResponse)(nil), "protos.TaskProcessResponse")
	proto.RegisterType((*TaskStartRequest)(nil), "protos.TaskStartRequest")
	proto.RegisterType((*TaskStartResponse)(nil), "protos.TaskStartResponse")
	proto.RegisterType((*PingRequest)(nil), "protos.PingRequest")
}

func init() { proto.RegisterFile("dister.proto", fileDescriptor_ffb07b0a572790a9) }

var fileDescriptor_ffb07b0a572790a9 = []byte{
	// 780 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5f, 0x6f, 0x23, 0x35,
	0x10, 0xaf, 0x9d, 0xec, 0xb6, 0x99, 0xe4, 0x7a, 0xdb, 0x69, 0xef, 0x58, 0x38, 0x01, 0xc1, 0xe8,
	0x44, 0xa4, 0x8a, 0x08, 0x05, 0x21, 0x24, 0x84, 0x90, 0x4a, 0x6f, 0xa9, 0x22, 0x7a, 0x69, 0xce,
	0xbb, 0xe5, 0x35, 0xda, 0xcb, 0x5a, 0xed, 0xea, 0xb2, 0x7f, 0x58, 0x3b, 0x91, 0xf2, 0x8a, 0xc4,
	0xf7, 0xe0, 0x8d, 0x2f, 0x01, 0x8f, 0x88, 0x2f, 0xc0, 0x07, 0x42, 0xf6, 0x7a, 0xd3, 0xbd, 0xc0,
	0x3d, 0xcd, 0xcc, 0x6f, 0x66, 0xec, 0x9f, 0xc7, 0x3f, 0x1b, 0x06, 0x49, 0x2a, 0x95, 0xa8, 0xc6,
	0x65, 0x55, 0xa8, 0x02, 0x5d, 0x63, 0x24, 0xfb, 0x06, 0xfa, 0x2f, 0x85, 0x94, 0xf1, 0x9d, 0xb8,
	0x4e, 0xa5, 0xc2, 0x73, 0x38, 0xca, 0xea, 0x50, 0xfa, 0x64, 0xd8, 0x19, 0xf5, 0x27, 0x8f, 0xeb,
	0x06, 0x39, 0xb6, 0x65, 0x7c, 0x57, 0xc0, 0xfe, 0xa1, 0x70, 0x68, 0x51, 0xfc, 0x0e, 0x06, 0x16,
	0x5f, 0xa8, 0x6d, 0x29, 0x7c, 0x32, 0x24, 0xa3, 0xe3, 0xc9, 0xb3, 0xbd, 0xe6, 0xc6, 0x46, 0xdb,
	0x52, 0xf0, 0x7e, 0xf6, 0x10, 0xe0, 0x73, 0x38, 0x5e, 0x16, 0x55, 0x25, 0x56, 0xb1, 0x4a, 0x8b,
	0x7c, 0x91, 0x26, 0x3e, 0x1d, 0x92, 0x51, 0x8f, 0x3f, 0x6a, 0xa1, 0xd3, 0x04, 0x7d, 0x38, 0x5c,
	0x16, 0xb9, 0x12, 0xb9, 0xf2, 0x3b, 0x43, 0x32, 0x1a, 0xf0, 0x26, 0x64, 0x7f, 0x93, 0xdd, 0x49,
	0xcc, 0x82, 0x67, 0xe0, 0xf1, 0xe0, 0x6a, 0x1a, 0x46, 0x01, 0x5f, 0xf0, 0xe0, 0xd5, 0x6d, 0x10,
	0x46, 0xde, 0x01, 0x3e, 0x81, 0x93, 0x16, 0x1a, 0xce, 0x6f, 0x66, 0x61, 0xe0, 0x11, 0xf4, 0xe1,
	0x2c, 0xba, 0x08, 0x7f, 0x5c, 0xcc, 0xf9, 0xcd, 0x65, 0x10, 0x86, 0xbb, 0x06, 0x8a, 0xef, 0xc3,
	0x93, 0xbd, 0x8c, 0x6d, 0xea, 0xe0, 0x53, 0x40, 0x93, 0x0a, 0xa3, 0x0b, 0x1e, 0xed, 0x5a, 0xba,
	0xf8, 0x1e, 0x9c, 0xbe, 0x85, 0xdb, 0x06, 0x07, 0x4f, 0x60, 0x30, 0x9f, 0xce, 0xae, 0x76, 0xa5,
	0x7f, 0x38, 0x88, 0xf0, 0xc8, 0x42, 0xb6, 0xea, 0x4f, 0x87, 0x7d, 0x05, 0x8f, 0xb9, 0xb8, 0x33,
	0x97, 0xc5, 0xc5, 0xcf, 0x6b, 0x21, 0x15, 0x7a, 0xd0, 0x59, 0x96, 0x6b, 0x33, 0x54, 0x87, 0x6b,
	0x57, 0x23, 0x99, 0xc8, 0xcc, 0x90, 0x1c, 0xae, 0x5d, 0xc6, 0xc0, 0x7b, 0x68, 0x93, 0x65, 0x91,
	0x4b, 0x81, 0xc7, 0x40, 0xd3, 0xc4, 0xb4, 0xf5, 0x38, 0x4d, 0x13, 0xf6, 0x1b, 0x01, 0x8c, 0x62,
	0xf9, 0x66, 0x5e, 0x15, 0x4b, 0x21, 0x65, 0xb3, 0xfc, 0x5e, 0x99, 0x9e, 0xb2, 0xba, 0xaf, 0x44,
	0x9c, 0x48, 0xbb, 0x41, 0x13, 0xe2, 0xc7, 0xd0, 0x5f, 0x16, 0xeb, 0x5c, 0x2d, 0x56, 0x69, 0x96,
	0xd6, 0x77, 0xe0, 0x70, 0x30, 0xd0, 0xb5, 0x46, 0xf0, 0x43, 0x00, 0x95, 0x66, 0xc2, 0xe6, 0xbb,
	0x26, 0xdf, 0xd3, 0x48, 0x9d, 0x1e, 0x42, 0x57, 0xc5, 0xf2, 0x8d, 0xef, 0x0c, 0xc9, 0xa8, 0x3f,
	0x19, 0x34, 0xf2, 0xd0, 0x9c, 0xb8, 0xc9, 0xb0, 0xdf, 0x09, 0xf4, 0x7e, 0x8a, 0x57, 0x69, 0x12,
	0xab, 0xa2, 0x42, 0x84, 0x6e, 0x1e, 0x67, 0xc2, 0x72, 0x33, 0x3e, 0x9e, 0x03, 0xdd, 0x28, 0x43,
	0xac, 0x25, 0xb0, 0x5d, 0x4b, 0xed, 0x19, 0x81, 0xd1, 0x8d, 0xc2, 0x33, 0x70, 0x36, 0xf1, 0x6a,
	0x2d, 0x0c, 0xd5, 0x1e, 0xaf, 0x03, 0x76, 0x69, 0xf7, 0x30, 0x4a, 0x71, 0x81, 0x5e, 0x6b, 0x6d,
	0x68, 0xab, 0xc5, 0xe0, 0x02, 0x0d, 0x5e, 0x79, 0x54, 0xdb, 0x99, 0xbe, 0x67, 0x17, 0xe8, 0x55,
	0xe0, 0x75, 0x8d, 0x8d, 0x3c, 0x47, 0xdb, 0xe9, 0xcc, 0x73, 0xd9, 0x5f, 0x04, 0xba, 0x9a, 0xb8,
	0xbe, 0x8b, 0x75, 0xb5, 0xb2, 0x1c, 0xb5, 0xab, 0x69, 0x97, 0xb1, 0xba, 0xb7, 0x1a, 0x36, 0x3e,
	0x9e, 0x83, 0x9b, 0x09, 0x75, 0x5f, 0x24, 0x86, 0xca, 0xf1, 0xe4, 0xb4, 0x7d, 0xf8, 0xf1, 0x4b,
	0x93, 0xe2, 0xb6, 0x44, 0x2f, 0xf0, 0xba, 0x48, 0xb6, 0x66, 0x80, 0x03, 0x6e, 0x7c, 0x7c, 0x0a,
	0xae, 0x5c, 0x56, 0x69, 0xa9, 0xcc, 0xf4, 0x7a, 0xdc, 0x46, 0xf8, 0x09, 0xd0, 0x8d, 0xf4, 0x5d,
	0xf3, 0x5a, 0x4f, 0xfe, 0x33, 0x0f, 0x4e, 0x37, 0x92, 0x3d, 0x03, 0xb7, 0xde, 0x00, 0x0f, 0xa1,
	0x73, 0x15, 0xe8, 0xd3, 0x1e, 0x41, 0x77, 0x7e, 0x13, 0x46, 0x1e, 0x61, 0xbf, 0x12, 0x38, 0x7d,
	0x4b, 0x14, 0xff, 0x2f, 0x1e, 0xfc, 0x1a, 0x68, 0xd9, 0xcc, 0xfd, 0xb3, 0x36, 0xf9, 0xbd, 0xc6,
	0xf1, 0xbc, 0x12, 0x65, 0x5c, 0xd5, 0x8f, 0x9c, 0x96, 0x8a, 0x3d, 0x87, 0x7e, 0x0b, 0xc2, 0x3e,
	0x1c, 0x86, 0xb7, 0x97, 0xfa, 0x35, 0x79, 0x07, 0xd8, 0x03, 0xe7, 0x87, 0x8b, 0xe9, 0xf5, 0x0b,
	0x8f, 0x68, 0x01, 0xeb, 0xd5, 0x42, 0x15, 0x57, 0xea, 0x1d, 0xca, 0x64, 0x9f, 0xc2, 0x49, 0xab,
	0xe6, 0x1d, 0x2a, 0xff, 0x85, 0x40, 0x7f, 0x9e, 0xe6, 0x77, 0xcd, 0x22, 0x63, 0xa0, 0x52, 0xd9,
	0x1f, 0xe9, 0xa3, 0x86, 0x78, 0xab, 0x60, 0x1c, 0xaa, 0x58, 0xad, 0x2d, 0x5f, 0x69, 0x34, 0xa3,
	0xa5, 0xa8, 0xc5, 0xdf, 0xd1, 0x9a, 0x31, 0x01, 0xfb, 0x1c, 0xe0, 0xa1, 0x4e, 0x8f, 0xef, 0xfb,
	0xb5, 0xdc, 0xd6, 0x83, 0x9c, 0x26, 0x2b, 0xe1, 0x11, 0x7d, 0xb0, 0xdb, 0x9c, 0x8b, 0x38, 0xd9,
	0x7a, 0x74, 0xf2, 0x2d, 0xb8, 0x2f, 0xcc, 0x63, 0xc4, 0x09, 0x1c, 0x55, 0xf6, 0x61, 0xe2, 0xfe,
	0x6f, 0xfa, 0xc1, 0x3e, 0xc0, 0x0e, 0x46, 0xe4, 0x0b, 0xf2, 0xba, 0xfe, 0x9e, 0xbf, 0xfc, 0x37,
	0x00, 0x00, 0xff, 0xff, 0xf9, 0xb0, 0x64, 0x08, 0xb5, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DisterClient is the client API for Dister service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DisterClient interface {
	Register(ctx context.Context, opts ...grpc.CallOption) (Dister_RegisterClient, error)
}

type disterClient struct {
	cc *grpc.ClientConn
}

func NewDisterClient(cc *grpc.ClientConn) DisterClient {
	return &disterClient{cc}
}

func (c *disterClient) Register(ctx context.Context, opts ...grpc.CallOption) (Dister_RegisterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dister_serviceDesc.Streams[0], "/protos.Dister/register", opts...)
	if err != nil {
		return nil, err
	}
	x := &disterRegisterClient{stream}
	return x, nil
}

type Dister_RegisterClient interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ClientStream
}

type disterRegisterClient struct {
	grpc.ClientStream
}

func (x *disterRegisterClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *disterRegisterClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DisterServer is the server API for Dister service.
type DisterServer interface {
	Register(Dister_RegisterServer) error
}

// UnimplementedDisterServer can be embedded to have forward compatible implementations.
type UnimplementedDisterServer struct {
}

func (*UnimplementedDisterServer) Register(srv Dister_RegisterServer) error {
	return status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterDisterServer(s *grpc.Server, srv DisterServer) {
	s.RegisterService(&_Dister_serviceDesc, srv)
}

func _Dister_Register_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DisterServer).Register(&disterRegisterServer{stream})
}

type Dister_RegisterServer interface {
	Send(*Message) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type disterRegisterServer struct {
	grpc.ServerStream
}

func (x *disterRegisterServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func (x *disterRegisterServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Dister_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Dister",
	HandlerType: (*DisterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "register",
			Handler:       _Dister_Register_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "dister.proto",
}
